- $formkit: 'text'
  name: 'appKey'
  value: '$appKey'
  label: 'AppKey'
  help: '您的百度网盘开放平台应用AppKey'
  validation: 'required|length:5,40'

- $formkit: 'text'
  name: 'secretKey'
  value: '$secretKey'
  label: 'SecretKey'
  help: '您的百度网盘开放平台应用SecretKey'
  validation: 'required|length:5,40'

- $formkit: 'text'
  name: 'accessToken'
  value: '$accessToken'
  label: 'AccessToken'
  help: '您的百度网盘开放平台获取的AccessToken'
  validation: 'required|length:5,40'

- $formkit: 'text'
  name: 'refreshToken'
  value: '$refreshToken'
  label: 'RefreshToken'
  help: '您的百度网盘开放平台获取的RefreshToken'
  validation: 'required|length:5,40'


